language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - DB=mysql
  - DB=postgres
before_script:
  - "mysql -e 'create database social_stream_test;'"
  - "psql -c 'create database social_stream_test;' -U postgres"

# blacklist
branches:
  except:
    - staging
